runtime: python38
instance_class: F1
env_variables: 
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'team43'
  MYSQL_DB: 'database43'
  MYSQL_HOST: '34.121.41.4'
handlers:
- url: /img
  static_dir: static/img
- url: /script
  static_dir: static/script
- url: /styles
  static_dir: static/styles
